<a href="https://colab.research.google.com/github/AkshayNikam123/python-topicwise/blob/main/array%2Cmatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from array import *

In [ ]:
vals=array('i',[2,3,4,5])
print(vals)

array('i', [2, 3, 4, 5])


In [ ]:
vals=array('i',[2,3.5,4,5]) #i is for integer
print(vals)

TypeError: ignored

In [ ]:
vals=array('i',[-2,3,4,-5])
print(vals)

array('i', [-2, 3, 4, -5])


In [ ]:
vals=array('I',[2,3,4,5])
print(vals)

array('I', [2, 3, 4, 5])


In [ ]:
vals=array('I',[-2,3,4,-15]) #I is only for positive int
print(vals)

OverflowError: ignored

In [ ]:
print(vals.buffer_info()) #location,size

(140049433684416, 4)


In [ ]:
vals=array('i',[2,3,4,15])
vals.reverse()
print(vals)

array('i', [15, 4, 3, 2])


In [ ]:
print(vals[2])

3


In [ ]:
for i in vals:
  print(i)

15
4
3
2


In [ ]:
newarray=array(vals.typecode,(a for a in vals)) #copy array
for i in newarray:
  print(i)

15
4
3
2


In [ ]:
newarray1=array(vals.typecode,(a*a for a in vals))
for i in newarray1:
  print(i)

225
16
9
4


In [ ]:
i=0
while i<len(newarray):
  print(newarray[i])
  i+=1

15
4
3
2


In [ ]:
arr=array('i',[])
n=int(input("enter the length of array"))
for i in range(n):
  x=int(input("enter the value"))
  arr.append(x)

print(arr)

enter the length of array5
enter the value23
enter the value34
enter the value55
enter the value56
enter the value56
array('i', [23, 34, 55, 56, 56])


In [ ]:
var=int(input("enter the value for search"))
k=0
for e in arr:
  if e==var:
    print(k)
    break  
  k+=1

enter the value for search56
3


In [ ]:
arr=array('i',[])
n=int(input("enter the length of array"))
for i in range(n):
  x=int(input("enter the value"))
  arr.append(x)

print(arr)
var=int(input("enter the value for search"))
k=0
"""for e in arr:
  if e==var:
    print(k)
    break  
  k+=1"""
"or"
print(arr.index(var))

enter the length of array4
enter the value12
enter the value23
enter the value34
enter the value45
array('i', [12, 23, 34, 45])
enter the value for search34
2
2


In [ ]:
from numpy import *

arr=array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:

arr=array([1,2,3,4.0])
print(arr.dtype)

float64


In [ ]:

arr=array([1,2,3,4],float)
print(arr.dtype)

float64


In [ ]:

arr=array([1,2,3,4.0],int)
print(arr.dtype)

int64


In [ ]:
#linspace()
arr=linspace(0,16,15)
print(arr)

[ 0.          1.14285714  2.28571429  3.42857143  4.57142857  5.71428571
  6.85714286  8.          9.14285714 10.28571429 11.42857143 12.57142857
 13.71428571 14.85714286 16.        ]


In [ ]:
arr=linspace(0,16)
print(arr)

[ 0.          0.32653061  0.65306122  0.97959184  1.30612245  1.63265306
  1.95918367  2.28571429  2.6122449   2.93877551  3.26530612  3.59183673
  3.91836735  4.24489796  4.57142857  4.89795918  5.2244898   5.55102041
  5.87755102  6.20408163  6.53061224  6.85714286  7.18367347  7.51020408
  7.83673469  8.16326531  8.48979592  8.81632653  9.14285714  9.46938776
  9.79591837 10.12244898 10.44897959 10.7755102  11.10204082 11.42857143
 11.75510204 12.08163265 12.40816327 12.73469388 13.06122449 13.3877551
 13.71428571 14.04081633 14.36734694 14.69387755 15.02040816 15.34693878
 15.67346939 16.        ]


In [ ]:
arr=arange(1,15,5)
print(arr)

[ 1  6 11]


In [ ]:
arr=logspace(1,15,3)
print(arr)

[1.e+01 1.e+08 1.e+15]


In [ ]:
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr=zeros(5,int)
print(arr)

[0 0 0 0 0]


In [ ]:
arr=ones(5,int)
print(arr)



[1 1 1 1 1]


In [ ]:
#

In [ ]:
arr=array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


In [ ]:
arr1=array([1,2,3,4,5])
arr2=array([6,7,8,9,0])
arr3=arr1+arr2
print(arr3)


[ 7  9 11 13  5]


In [ ]:
from numpy import *
print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(sqrt(arr2))

[2.44948974 2.64575131 2.82842712 3.         0.        ]


In [ ]:
print(concatenate([arr1,arr2]))

[1 2 3 4 5 6 7 8 9 0]


In [ ]:
#copy array
arr1=array([1,2,3,4])
arr2=arr1
print(arr2)

[1 2 3 4]


In [ ]:
print(id(arr1),id(arr2))

140049219465360 140049219465360


In [ ]:
arr1=array([1,2,3,4])
arr2=arr1.view() #view gives two different location to arrays
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3 4]
140049220046448
140049219529008


In [ ]:
arr1=array([1,2,3,4])
arr2=arr1.view()
arr1[1]=5   #shallow copy change both for
print(arr2)
print(id(arr1))
print(id(arr2))

[1 5 3 4]
140049219465552
140049219526896


In [ ]:
arr1=array([1,2,3,4])
arr2=arr1.copy()   #deep copy no change in second array
arr1[1]=6
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 6 3 4]
[1 2 3 4]
140049219465360
140049219529392


#metrics

In [ ]:
arr1=array([
    [1,2,3],[2,3,4]
])
print(arr1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(arr1.ndim)

2


In [ ]:
print(arr1.shape)

(2, 3)


In [ ]:
print(arr1.size)

6


In [ ]:
arr2=arr1.flatten()
print(arr2)

[1 2 3 2 3 4]


In [ ]:
arr3=arr2.reshape(2,2)

ValueError: ignored

In [ ]:
arr3=arr2.reshape(3,2)
print(arr3)

[[1 2]
 [3 2]
 [3 4]]


In [ ]:
arr=array([1,2,3,4,5,6,7,8,9,0,12,34])
arr1=arr.reshape(2,2,3)
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 0 12 34]]]


In [ ]:
#matrix
arr=array([
    [1,2,3,4],
    [2,3,4,5]
])

m=matrix(arr)
print(m)

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
m=matrix('1,2,3;2,3,4;4,5,6')
print(m)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [ ]:
print(m.min())
print(m.max())
print(m.diagonal())

1
6
[[1 3 6]]


In [ ]:
m1=matrix('1,2,3;2,3,4;5,6,7')
m2=matrix('2,3,4;3,4,5;7,8,9')
m3=m1*m2
print(m3)

[[ 29  35  41]
 [ 41  50  59]
 [ 77  95 113]]
